### ISSUE TITLE
Can we add PKCE? 

### ISSUE THREAD

**Issue by wuarmin** [adfinis/ember-simple-auth-oidc#292]
Hello, 
thanks for this addon. It is great. 

For ember apps Authorization Code Flow with PKCE is recommended. Would it be possible to add support for it?

Best regards

**Comment by bjornharrtell** [comment]
@wuarmin that is what is supported.

**Comment by wuarmin** [comment]
@bjornharrtell thank you, are you sure? https://oauth.net/2/pkce/

**Comment by bjornharrtell** [comment]
@wuarmin I'm not 100% sure but I'm successfully using it with two different IdPs that offer Authorization Code Flow with PKCE. As there is no client secret I assumed it would not work if it didn't properly support Authorization Code Flow with PKCE.

**Comment by turbcool** [comment]
PKCE authorization does not work for me (I use IdentityServer4)

**Comment by bjornharrtell** [comment]
agreed I was mistaken, PKCE is not implemented in this addon (yet)

**Comment by derrabauke** [comment]
Closing this, as PKCE is [implemented]. Please open a new issue if `PKCE` does not work out for you.
