### ISSUE TITLE
Missing support for required param code_challenge

### ISSUE THREAD

**Issue by bjornharrtell** [adfinis/ember-simple-auth-oidc#323]
Seems some IdPs do not require it but other do. It does seem like it is a required param according to section 4.3 in 
https://tools.ietf.org/html/rfc7636.

**Comment by wuarmin** [comment]
This is the same as #292

**Comment by Yelinz** [comment]
PKCE was implemented, let us know if it doesnt work for you https://github.com/adfinis/ember-simple-auth-oidc/issues/292#issuecomment-1516049644
