### ISSUE TITLE
Support dynamic client_id ?

### ISSUE THREAD

**Issue by ptgamr** [adfinis/ember-simple-auth-oidc#481]
Currently, we mount our app is mounted to a dynamic segment of the URL, what we would need to do is to use different `client_id` depending on the URL.

http://localhost:4200/namespace1  - use `client_id = namespace1`
http://localhost:4200/namespace2  - use `client_id = namespace2`
http://localhost:4200/namespace3  - use `client_id = namespace3`
...

It is not possible at the moment because the `client_id` is defined fixed inside `environment.js` file, and we only build 1 app. Would you have any suggestion how to achieve this? Can we somehow modify a config at runtime? or perhaps provide a function to get out values like: client_id, host, tokenEndpoint etc....

I might need some input here, happy to submit  a PR once I know more about how the API should look like.

Thanks,

**Comment by Yelinz** [comment]
Sorry for letting this issue slip.

Some changes would probably need to be made in how the config is initialized/ consumed.

https://github.com/adfinis/ember-simple-auth-oidc/blob/main/addon/config.js

The `config` function would probably need to be changed that you can defined an own function which returns the correct config based on some parameters.

Feel free to reopen if its still relevant to you.
Probably similar to https://github.com/adfinis/ember-simple-auth-oidc/issues/567
