### ISSUE TITLE
Manage multiple IDP configuration

### ISSUE THREAD

**Issue by yahyayouness** [adfinis/ember-simple-auth-oidc#567]
Thanks for this addon 👍 .

Actually we can manage one identity provider in the configuration. it is planned to manage multiple IDP configuration ?

**Comment by Yelinz** [comment]
Sorry for letting this issue slip.

Refer to answer to similar question here https://github.com/adfinis/ember-simple-auth-oidc/issues/481#issuecomment-2346651417

Currently not planned to support multiple IDPs at the same time.

Feel free to reopen if its still relevant to you.
