### ISSUE TITLE
Relative/dynamic afterLogoutUri

### ISSUE THREAD

**Issue by miguelcobain** [adfinis/ember-simple-auth-oidc#580]
Currently, this addon requires us to specify the `afterLogoutUri` at build time.
Would you be open to making the `afterLogoutUri` be computed at runtime?

I was thinking of using something relative to `window.location.origin`.
So, if you specify a `afterLogoutUri` value of `/home` and you're at `http://localhost:4200/`, the resulting url would be `http://localhost:4200/home`.

I'm willing to make a PR for this, but it would be nice to have some guidance, like should I use a new config property? Under which name? etc.

**Comment by anehx** [comment]
Hi @miguelcobain 

IMO this should already work. The `afterLogoutUri` will automatically be prepended with the current host if it's not absolute already:
https://github.com/adfinis-sygroup/ember-simple-auth-oidc/blob/4ccc20858b7c37021acfa804818bc8fa8dd65c55/addon/unauthorized.js#L15-L17
https://github.com/adfinis-sygroup/ember-simple-auth-oidc/blob/d83422e1ed43958af8b2039c81337d10320ac884/addon/authenticators/oidc.js#L107-L109
https://github.com/adfinis-sygroup/ember-simple-auth-oidc/blob/d6f9ccfa4cbacca94e7c8d50653f064a3f3fbb06/addon/utils/absolute-url.js#L1-L3

With what version did you try this?

**Comment by derrabauke** [comment]
Hi @miguelcobain, is this issue still relevant or can we close this?

**Comment by miguelcobain** [comment]
@anehx seems to be right. It should already work. My apologies.
